### ISSUE TITLE
data_utterance_pb2 is missing

### ISSUE THREAD

**Issue by chenchy** [guanlongzhao/fac-via-ppg#1]
Thank you for the great work. 
I try to run the code, but found data_utterance_pb2 missed.
Can you upload it ?

Thank you very much.

**Comment by guanlongzhao** [comment]
After you've installed all the dependency, you need to compile the protobuffer file `data_utterance.proto` to generate the `data_utterance_pb2.py` file using this command, `protoc -I=src/common --python_out=src/common src/common/data_utterance.proto`. See the install guide in the readme file for more details.

**Comment by chenchy** [comment]
@guanlongzhao Thank you very much!
