### ISSUE TITLE
Question about am speaker adpatation

### ISSUE THREAD

**Issue by labccin** [guanlongzhao/fac-via-ppg#10]
Hi. Thanks for continuing the fantastic work.

I am trying out your approach, and was wondering if the PPG extraction in your paper was speaker adaptive. 

Your paper for this repository does not mention speaker adaptation. However both  <Using phonetic posteriorgram based frame pairing for segmental accent conversion (2019)> and <Accent conversion using phonetic posteriorgrams (2018)> say they used speaker-indepent AM. 

Below is the feature extraction procedure in compute_ppg.py in this repository. I don't see fmllr or ivector in the procedure, so was wondering if there was something else applied, or you simply did not used speaker-adpated model for this work.

Thank you!

```python
    # Get MFCCs
    mfcc_opts = MfccOptions()
    mfcc_opts.use_energy = options["is_use_energy"]
    mfcc_opts.frame_opts.allow_downsample = options["is_downsample"]
    mfcc_opts.frame_opts.frame_shift_ms = options["frame_shift"]
    mfcc_opts.frame_opts.snip_edges = options["is_snip_edges"]
    mfccs = feat.compute_mfcc_feats(wav, mfcc_opts)

    # Apply CMN
    mfccs = feat.apply_cepstral_mean_norm(mfccs)

    # Splice feats
    feats = splice_frames(mfccs,
                          options["left_context"], options["right_context"])

    # Apply LDA
    feats = feat.apply_feat_transform(feats, lda)
```

**Comment by guanlongzhao** [comment]
Hi, we did not use any speaker-dependent model for our work. Although it won't be hard to extend this codebase to use speaker-adapted models. Feel free to give it a try : )

**Comment by labccin** [comment]
I see, thank you!!!
