### ISSUE TITLE
LDA reducre matrix transform

### ISSUE THREAD

**Issue by AghilasSini** [guanlongzhao/fac-via-ppg#12]
Hi,
First of all, thank you for this exciting work, and thanks for sharing it on GitHub.

I am trying to reproduce your work but in a different language, French instead of English.

I wonder how you got the LDA.mat  of '40X91', but in my case, the LDA matrix is "40X281"?

Thanks a lot

**Comment by guanlongzhao** [comment]
Did you compute your own LDA matrix instead of using the one in the repo?

**Comment by AghilasSini** [comment]
Hi,

Thank you so much for you quick answer. I think that I solved the problem of LDA matrix (Kaldi related issue actually we are using different acoustic model type from those you are using).
Nowadays I am facing an other problem related to the reduced matrix that allows to reduce from raw PPGS to monophone PPGS? how did you get this transform sparce matrix for English? [senones X phonemes] 

Thanks a lot

**Comment by guanlongzhao** [comment]
Please take a look at this https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/nnet3/chain/get_phone_post.sh#L202-L206, especially the referred lines to get an idea of how to get the transform matrix. Bascially you need to get the symbol table of the output layer and consolidating them into phonemes; the transformation can be represented by a matrix multiplication.
