### ISSUE TITLE
How to train acoustic model and preprocessing PPG

### ISSUE THREAD

**Issue by monist-david** [guanlongzhao/fac-via-ppg#14]
I don't understand how your code is completing the  "3.1 Acoustic modeling and PPG extraction" section you mentioned in the paper. Could you explain that part a little bit please? Thanks!

**Comment by guanlongzhao** [comment]
The AM training was done entirely through kaldi, this repo only contains the pre-trained AM model file and the PPG extraction logic, which can be found in https://github.com/guanlongzhao/fac-via-ppg/blob/master/src/ppg/compute_ppg.py
