### ISSUE TITLE
trainning is too slow

### ISSUE THREAD

**Issue by audier** [guanlongzhao/fac-via-ppg#2]
hi, guanlong.
Could you tell me how long it costs per iteration in your trainning?
I think there's some mistake when I run your script 'python train_ppg2mel.py'.
![image](https://user-images.githubusercontent.com/37586343/64688171-5f582e00-d4be-11e9-98bd-dd9dedb12742.png)

**Comment by guanlongzhao** [comment]
> hi, guanlong.
> Could you tell me how long it costs per iteration in your trainning?
> I think there's some mistake when I run your script 'python train_ppg2mel.py'.
> ![image](https://user-images.githubusercontent.com/37586343/64688171-5f582e00-d4be-11e9-98bd-dd9dedb12742.png)

If you are using a good GPU it should not take too much time per iteration. I don't remember the exact details but your training speed looked normal to me. I was using a 1070 GPU and it takes about eight hours to train a good model on one hour of speech.
