### ISSUE TITLE
'protoc' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by barkhasharma082** [guanlongzhao/fac-via-ppg#3]
Hi, I am trying to follow the instruction on win10 x 64 however with this "protoc -I=src/common --python_out=src/common src/common/data_utterance.proto" I am getting the following error: 'protoc' is not recognized as an internal or external command,
operable program or batch file.

Would be great if I can get help ASAP!!

Thanks in Advance

**Comment by guanlongzhao** [comment]
We do not currently support Windows. The package has only been tested on Ubuntu 16.04. That being said, the problem you ran into is more generic -- your OS could not find where the protocol buffer compiler (`protoc`) is. It is either that the compiler was not properly installed, or it is not included in the system search path.
