### ISSUE TITLE
ModuleNotFoundError: No module named 'common.fp16_optimizer'

### ISSUE THREAD

**Issue by barkhasharma082** [guanlongzhao/fac-via-ppg#4]
I am getting this error when running train_ppg2mel.py model, I tried googling around and nothing worked, would be great if I can find a help!! Thanks in advance.

**Comment by guanlongzhao** [comment]
You probably did not include `YOUR_LOCAL_DIR/src` in your system's `PYTHONPATH`. See the install guide in the readme file for more details.
