### ISSUE TITLE
ModuleNotFoundError: No module named 'kaldi'

### ISSUE THREAD

**Issue by barkhasharma082** [guanlongzhao/fac-via-ppg#6]
Hi, I have been struggling with this error since past week and unable to find a working solution to this, I have already installed Kaldi in my system however when I run the "train_ppg2mel.py" I run into this error. 

Traceback (most recent call last):
  File "script/train_ppg2mel.py", line 42, in <module>
    from common.fp16_optimizer import FP16_Optimizer
  File "/mnt/c/Users/Bharkha/Desktop/Barkha_office/Accent_Conversion/fac-via-ppg/src/common/__init__.py", line 1, in <module>
    from .decode import *
  File "/mnt/c/Users/Bharkha/Desktop/Barkha_office/Accent_Conversion/fac-via-ppg/src/common/decode.py", line 17, in <module>
    from kaldi import nnet3
ModuleNotFoundError: No module named 'kaldi'

I am using WSL on win10x64 and till now everything seems to be working perfectly until I ran into this error. 

Any help will be appreciated, 
Thanks in advance

**Comment by guanlongzhao** [comment]
I think the error message explains itself,

>ModuleNotFoundError: No module named 'kaldi'

Please read the readme file closely. We use the `pykaldi` package not the official Kaldi toolkit directly, which is in C++.

Also, the code probably won't work on either Windows 10 or its Linux subsystem, though I have not tested that.

**Comment by barkhasharma082** [comment]
> I think the error message explains itself,
> 
> > ModuleNotFoundError: No module named 'kaldi'
> 
> Please read the readme file closely. We use the `pykaldi` package not the official Kaldi toolkit directly, which is in C++.
> 
> Also, the code probably won't work on either Windows 10 or its Linux subsystem, though I have not tested that.

Hi, thanks for the response. I already have pykaldi installed however it still throws the error "ModuleNotFoundError: No module named 'kaldi'", it was working fine so far until this stage.

**Comment by guanlongzhao** [comment]
> > I think the error message explains itself,
> > > ModuleNotFoundError: No module named 'kaldi'
> > 
> > 
> > Please read the readme file closely. We use the `pykaldi` package not the official Kaldi toolkit directly, which is in C++.
> > Also, the code probably won't work on either Windows 10 or its Linux subsystem, though I have not tested that.
> 
> Hi, thanks for the response. I already have pykaldi installed however it still throws the error "ModuleNotFoundError: No module named 'kaldi'", it was working fine so far until this stage.

In that case, I would recommend consulting the `pykaldi` folks since we are just using their package. You can find them here, https://github.com/pykaldi/pykaldi

**Comment by meharbhatia** [comment]
Facing the same issue, though everything was working well last week.
