### ISSUE TITLE
Question about model application

### ISSUE THREAD

**Issue by nestyme** [guanlongzhao/fac-via-ppg#7]
Hi!
Wonderful project!
I would like to know, if it is possible to apply proposed approach for voice morphing? 
For example, to train model on young and old voices and create age morphing system? 
I still can't figure out why it won't work but maybe some reasons exist :)
Thanks!

**Comment by guanlongzhao** [comment]
Thanks for your interest! This project was not designed for voice morphing, but potentially you can train a model with adult speech and perform inference with child utterances, and the output would sound like the adult speaking what the child said in the utterance. Obviously, you can do the reverse. Not sure if that's what you want though.

Regarding "can't figure out why it won't work," did you mean you ran into issues when you try to use the code? If so, please feel free to post logs/error messages/screenshots, and maybe I can offer some help.
